Models:
  post:
    columns:
      title: string
      body: text
      test: string
      test2: string
      test3: string
  #      test4: string

  tag:
    columns:
      biz: string
      baz: string

Pivot:
  post_tag:
    columns:
      tag_id:
      post_id:

Migrations:
  Mig1:
    columns:
      foo_mig: string
      bar_mig: string
